# Jackpot Bot Config (Stocks + Crypto + News)
data_sources:
  stocks: barchart
  crypto: coingecko
  news: cryptopanic

portfolio_file: sample_portfolio.csv
crypto_portfolio_file: sample_crypto_portfolio.csv

stock_universe:
  - AAPL
  - MSFT
  - NVDA
  - TSLA
  - SMCI
  - PLTR
  - AMD
  - MRNA
  - CCJ
  - NIO
  - RIVN
  - AI

crypto_universe:
  - bitcoin
  - ethereum
  - solana
  - avalanche-2
  - dogecoin
  - shiba-inu
  - pepe
  - toncoin
  - chainlink

indicators:
  - rsi
  - macd
  - sma50
  - sma200
  - volume_surge
  - sentiment

signals:
  strong_buy: 0.70
  weak_buy: 0.55
  neutral: 0.45
  sell: 0.30

alerts:
  telegram:
    enabled: true
    bot_token: ${TELEGRAM_BOT_TOKEN}
    chat_id: ${TELEGRAM_CHAT_ID}

openai:
  enabled: true
  api_key: ${OPENAI_API_KEY}
  model: gpt-4o-mini
