name: Jackpot Bot

on:
  workflow_dispatch:       # manual trigger
  schedule:
    - cron: '0 6-21 * * 1-5'  # hourly from 6AM to 9PM, Monday=1 to Friday=5

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
      QUESTRADE_CLIENT_ID: ${{ secrets.QUESTRADE_CLIENT_ID }}
      QUESTRADE_REFRESH_TOKEN: ${{ secrets.QUESTRADE_REFRESH_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Jackpot Bot
        run: python bot.py
