name: Jackpot Bot

on:
  schedule:
    - cron: '0 6-21 * * 1-5' # Mon-Fri, hourly 6AM-9PM
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Jackpot Bot
        run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          POLYGON_API_KEY: ${{ secrets.POLYGON_API_KEY }}
          QUESTRADE_CLIENT_ID: ${{ secrets.QUESTRADE_CLIENT_ID }}
          QUESTRADE_REFRESH_TOKEN: ${{ secrets.QUESTRADE_REFRESH_TOKEN }}
