name: Jackpot Bot GPT

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-and-run-bot:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Generate portfolio CSV via GPT
      - name: Generate portfolio CSV via ChatGPT
        run: python update_portfolio.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      # Commit updated CSV back to GitHub
      - name: Commit updated CSV
        run: |
          git config --global user.email "fixingsociety666@gmail.com"
          git config --global user.name "fixingsociety666-coder"
          git add sample_portfolio.csv
          git commit -m "Update sample_portfolio.csv via GPT workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      # Run Jackpot Bot for signals
      - name: Run Jackpot Bot
        run: python bot.py

      # Show signals in workflow logs
      - name: Show Signals
        run: |
          if [ -f signals/signals.csv ]; then
            echo "----- Jackpot Bot Signals -----"
            cat signals/signals.csv
          else
            echo "No signals generated."
          fi






