name: Jackpot Bot Scheduler

# Run manually or on schedule
on:
  workflow_dispatch:        # allows manual trigger
  schedule:
    - cron: "30 13 * * 1-5" # every weekday at 13:30 UTC (adjust as needed)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run the Jackpot Bot
      - name: Run Jackpot Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bot.py
