name: Jackpot Bot

on:
  schedule:
    - cron: '0 12 * * *'  # runs daily at 12:00 UTC
  workflow_dispatch:

jobs:
  update-and-run-bot:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # 4️⃣ Update portfolio CSV
      - name: Update portfolio CSV
        run: python update_portfolio.py

      # 5️⃣ Commit & push updated CSV back to GitHub
      - name: Commit updated CSV
        run: |
          git config --global user.email "fixingsociety666@gmail.com"
          git config --global user.name "fixingsociety666-coder"
          git add sample_portfolio.csv
          git commit -m "Update sample_portfolio.csv via workflow" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main

      # 6️⃣ Run Jackpot Bot
      - name: Run Jackpot Bot
        run: python bot.py

      # 7️⃣ Debug logs for signals
      - name: Show Signals
        run: |
          if [ -f signals/signals.csv ]; then
            echo "----- Jackpot Bot Signals -----"
            cat signa



